import json
import os
import shutil
import tempfile

from app.automation.account_rotator import account_rotator
from app.automation.grok import grok_automation
from app.config import settings
from app.database import async_session_factory
from app.processing.asset_manager import asset_manager
from app.processing.ffmpeg import ffmpeg_processor
from app.services.minio_client import minio_client
from app.services.scene_director import scene_director
from app.services.whisper import whisper_client
from app.utils.logger import logger


async def process_brolls(
    job_id: str,
    tts_audio_minio_path: str,
    script: str,
    language: str,
    db_session,
    system_prompt_scene_director: str | None = None,
    on_progress: callable = None,
) -> dict:
    """Stage 2 Track B: Generate B-Roll videos from scene analysis.

    Flow:
        1. Download TTS audio from MinIO
        2. Transcribe with Whisper (word-level timestamps)
        3. Scene Director LLM (semantic blocks + SFX + B-Roll prompts)
        4. Get Grok account (round-robin)
        5. Batch generate B-Rolls via Grok (batch_size tabs at a time)
        6. Upload all B-Rolls to MinIO
        7. Return structured data for Remotion

    Args:
        job_id: Unique job identifier.
        tts_audio_minio_path: MinIO path to the TTS audio file.
        script: The narration script text.
        language: BCP-47 language tag (e.g. ``"pt-BR"``).
        db_session: SQLAlchemy async session for account queries.
        system_prompt_scene_director: Optional custom system prompt for
            the Scene Director LLM.
        on_progress: Optional callback for progress updates.

    Returns:
        Dict with:
        - word_timestamps: list of {word, start, end}
        - scenes: list of scene blocks with broll_prompts and sfx
        - broll_paths: dict mapping scene_index -> MinIO path
        - urgent_keywords: list of keywords for BREAKING NEWS banner
        - total_duration: audio duration in seconds
        - prompts_used: list of prompts sent to Grok
    """
    print("[Track B] Iniciando processamento de B-Rolls...", flush=True)

    tmp_dir = tempfile.mkdtemp(prefix=f"brolls_{job_id}_")
    account = None

    try:
        # ── Step 1: Download TTS audio ────────────────────────────
        print("[Track B] 1/7 Baixando audio TTS do MinIO...", flush=True)

        audio_local = os.path.join(tmp_dir, "tts_audio.mp3")
        audio_data = minio_client.download_file(tts_audio_minio_path)
        with open(audio_local, "wb") as f:
            f.write(audio_data)

        total_duration = await ffmpeg_processor.get_duration(audio_local)
        print(f"[Track B] 1/7 Audio TTS: {len(audio_data)/1024:.0f}KB, duracao: {total_duration:.1f}s", flush=True)

        # ── Step 2: Whisper transcription ─────────────────────────
        print("[Track B] 2/7 Transcrevendo com Whisper (word-level)...", flush=True)

        word_timestamps = await whisper_client.transcribe_to_word_timestamps(
            audio_local, language=language
        )
        print(f"[Track B] 2/7 Whisper: {len(word_timestamps)} palavras transcritas", flush=True)

        timestamps_json = json.dumps(word_timestamps, ensure_ascii=False, indent=2)
        asset_manager.save_asset(
            job_id,
            "stage2_brolls",
            "word_timestamps.json",
            timestamps_json.encode(),
            "application/json",
        )

        # ── Step 3: Scene Director (LLM) ─────────────────────────
        print("[Track B] 3/7 Diretor de Cena analisando roteiro (LLM)...", flush=True)

        scene_data = await scene_director.direct_scenes(
            script=script,
            word_timestamps=word_timestamps,
            total_duration=total_duration,
            system_prompt=system_prompt_scene_director,
            broll_duration=settings.BROLL_DURATION_SECONDS,
        )

        scenes = scene_data.get("scenes", [])
        urgent_keywords = scene_data.get("urgent_keywords", [])
        print(f"[Track B] 3/7 Diretor de Cena: {len(scenes)} cenas, {len(urgent_keywords)} keywords", flush=True)

        scene_json = json.dumps(scene_data, ensure_ascii=False, indent=2)
        asset_manager.save_asset(
            job_id,
            "stage2_brolls",
            "scenes.json",
            scene_json.encode(),
            "application/json",
        )
        print("[Track B] 3/7 Cenas salvas no MinIO (scenes.json)", flush=True)

        # ── Step 4: Extract B-Roll prompts ────────────────────────
        prompts = [
            scene.get("broll_prompt", "")
            for scene in scenes
            if scene.get("broll_prompt")
        ]

        if not prompts:
            raise RuntimeError("[Track B] No B-Roll prompts generated by Scene Director")

        max_brolls = min(len(prompts), settings.BROLL_COUNT)
        prompts = prompts[:max_brolls]
        print(f"[Track B] 4/7 {len(prompts)} prompts de B-Roll extraidos:", flush=True)
        for i, p in enumerate(prompts):
            print(f"[Track B]   [{i+1}] {p[:80]}", flush=True)

        # ── Step 5: Get Grok account ─────────────────────────────
        print("[Track B] 5/7 Buscando conta Grok...", flush=True)
        async with async_session_factory() as fresh_db:
            account = await account_rotator.get_next_account("grok", fresh_db)
            if not account:
                raise RuntimeError("No active Grok accounts available")
            cookies = await account_rotator.get_account_cookies(account)
            proxy = await account_rotator.get_account_proxy(account)
        print(f"[Track B] 5/7 Conta Grok: {account.account_name} ({len(cookies)} cookies)", flush=True)

        # ── Step 6: Batch generate via Grok ──────────────────────
        print(f"[Track B] 6/7 Gerando {len(prompts)} B-Rolls com Grok...", flush=True)

        def _grok_progress(done: int, total: int, msg: str) -> None:
            print(f"[Track B] 6/7 B-Rolls: {done}/{total} - {msg}", flush=True)
            if on_progress:
                on_progress(f"B-Rolls: {done}/{total} - {msg}")

        broll_local_paths = await grok_automation.batch_generate(
            prompts=prompts,
            account_id=str(account.id),
            cookies=cookies,
            proxy=proxy,
            batch_size=settings.BROLL_BATCH_SIZE,
            max_retries=2,
            timeout_per_video=300,
            on_progress=_grok_progress,
        )

        await account_rotator.mark_account_used(account, success=True)
        print(f"[Track B] 6/7 Grok concluido: {len(broll_local_paths)} videos gerados", flush=True)

        # ── Step 7: Convert to 30fps + Upload to MinIO ────────────
        print(f"[Track B] 7/7 Convertendo B-Rolls para 30fps e subindo no MinIO...", flush=True)

        broll_minio_paths: dict[int, str] = {}
        for idx, local_path in broll_local_paths.items():
            if local_path and os.path.exists(local_path):
                converted_path = local_path.replace('.mp4', '_30fps.mp4')
                try:
                    import subprocess
                    subprocess.run(
                        ['ffmpeg', '-y', '-i', local_path,
                         '-r', '30', '-c:v', 'libx264', '-preset', 'fast',
                         '-crf', '23', '-an', converted_path],
                        capture_output=True, timeout=60,
                    )
                    upload_path = converted_path if os.path.exists(converted_path) else local_path
                except Exception:
                    upload_path = local_path

                filename = f"broll_{idx:02d}.mp4"
                minio_path = asset_manager.save_asset_from_file(
                    job_id, "stage2_brolls", filename, upload_path, "video/mp4"
                )
                broll_minio_paths[idx] = minio_path
                print(f"[Track B] 7/7 B-Roll {idx+1}/{len(prompts)} salvo no MinIO", flush=True)

        print(f"[Track B] CONCLUIDO: {len(broll_minio_paths)}/{len(prompts)} B-Rolls prontos!", flush=True)

        return {
            "word_timestamps": word_timestamps,
            "scenes": scenes,
            "broll_paths": broll_minio_paths,
            "urgent_keywords": urgent_keywords,
            "total_duration": total_duration,
            "prompts_used": prompts,
        }

    except Exception as e:
        # Mark account as failed if we got one
        if account is not None:
            try:
                await account_rotator.mark_account_used(
                    account, success=False, error_message=str(e)
                )
            except Exception:
                pass
        logger.error("[Track B] B-Roll processing failed: {err}", err=e)
        raise

    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        logger.debug("[Track B] Cleaned up temp dir: {tmp}", tmp=tmp_dir)
